[parity]
chain = "spec.json"
base_path = "parity_data"

[network]
reserved_peers="./bootnodes.txt"
port = 30303

[rpc]
apis = ["web3", "eth", "parity", "parity_set", "net", "traces", "rpc"]
interface = "all"
port=8545

[misc]
#log_file = "./logs/parity.log"
